# fly.toml app configuration file generated for studypro on 2024-11-10T05:18:14+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'studypro'
primary_region = 'nrt'

[deploy]
    strategy = "immediate"

[env]
    PORT = "8080"
    JAVA_TOOL_OPTIONS = "-Xmx512m"

[[services]]
    internal_port = 8080
    protocol = "tcp"
    processes = ["app"]

    [[services.ports]]
        handlers = ["http"]
        port = 80

    [[services.ports]]
        handlers = ["tls"]
        port = 443

    [services.concurrency]
        type = "connections"
        hard_limit = 25
        soft_limit = 20

    [[services.tcp_checks]]
        grace_period = "5s"
        interval = "10s"
        timeout = "2s"
        restart_limit = 3

[[services.http_checks]]
    interval = "15s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false

[build]
    image = "studypro:latest

[http_service]
    internal_port = 8080
    force_https = true
    auto_stop_machines = 'stop'
    auto_start_machines = true
    min_machines_running = 0
    processes = ['app']

[[vm]]
    memory = '512mb'
    cpu_kind = 'shared'
    cpus = 1
