spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${STUDYPRO_DB_URL}
    username: ${STUDYPRO_DB_USER}
    password: ${STUDYPRO_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  auth:
    key: ${STUDYPRO_JWT}
    accessTokenExpired: 3600000 # ms 단위(1시간)
    refreshTokenExpired: 25200000 # ms 단위(7시간)

domain: ${STUDYPRO_DOMAIN}
kakao:
  client_id: ${STUDYPRO_KAKAO_CLIENT_ID}
  redirect_url: ${STUDYPRO_KAKAO_REDIRECT_URL}
  token_url: https://kauth.kakao.com/oauth/token
  info_url: https://kapi.kakao.com/v2/user/me
  login_url: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=%s&redirect_uri=%s

firebase:
  apiKey: ${STUDYPRO_FIREBASE_API_KEY}
  authDomain: ${STUDYPRO_FIREBASE_AUTH_DOMAIN}
  projectId: ${STUDYPRO_FIREBASE_PROJECT_ID}
  storageBucket: ${STUDYPRO_FIREBASE_STORAGE_BUCKET}
  messagingSenderId: ${STUDYPRO_FIREBASE_MESSAGING_SENDER_ID}
  appId: ${STUDYPRO_FIREBASE_APP_ID}
  measurementId: ${STUDYPRO_FIREBASE_MEASUREMENT_ID}
  vapidKey: ${STUDYPRO_FIREBASE_VAPID_KEY}