spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/studypro
    username: root
    password: sinariari

  auth:
    key: dfsdsfdfsafseafesfaflsefjlijfilsjfilaesjfilejflajfiljile
    accessTokenExpired: 3600000
    refreshTokenExpired: 25200000
    url: https://kapi.kakao.com/v2/user/me
