spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:30000/studypro
    username: root
    password: password

  auth:
    key: dfsdsfdfsafseafesfaflsefjlijfilsjfilaesjfilejflajfiljile
    accessTokenExpired: 13221
    refreshTokenExpired: 21321
    url: https://kapi.kakao.com/v2/user/me
