# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Fly Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # GitHub 레포지토리 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # Java 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 환경 변수 파일 생성 (.env)
      - name: Create .env file
        run: |
          echo "${{ secrets.STUDYPRO_ENV }}" >> .env

      # Firebase JSON 파일 생성
      - name: Create Firebase credentials file
        run: |
          mkdir -p src/main/resources/firebase
          echo "${{ secrets.STUDYPRO_FIREBASE_CREDENTIALS }}" > src/main/resources/firebase/studypro-firebase-adminsdk.json

      # Gradle 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: clean build openapi3

      # Docker 이미지 빌드
      #      - name: Build Docker Image
      #        run: docker-compose build

      # Flyctl 설치
      - name: Install Flyctl
        #        uses: superfly/flyctl-actions/setup-flyctl@master
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "FLYCTL_INSTALL=$HOME/.fly" >> $GITHUB_ENV
          echo "PATH=$HOME/.fly/bin:$PATH" >> $GITHUB_ENV
      # Fly.io 로그인
      #      - name: Authenticate with Fly.io
      #        run: |
      #          export PATH="$HOME/.fly/bin:$PATH"
      #          fly auth login --access-token ${{ secrets.STUDYPRO_FLY_API_TOKEN }}

      # Fly.io 인증 확인
      - name: Authenticate Fly.io
        run: fly auth whoami
        env:
          FLY_API_TOKEN: ${{ secrets.STUDYPRO_FLY_API_TOKEN }}

      # Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t studypro:latest .
          docker images
      #          docker build -t studypro:latest .

      # 배포 중단 & Fly.io로 Docker 이미지 푸시
      - name: Push Docker Image to Fly.io
        run: |
          echo "${{ secrets.STUDYPRO_FLY_API_TOKEN }}"

          # 모든 머신 목록 가져오기
          MACHINES=$(fly machines list --app studypro --json | jq -r '.[].id')
          
          # 각 머신 중지
          for MACHINE in $MACHINES; do
            echo "Stopping machine $MACHINE"
            fly machines destroy $MACHINE --app studypro
          done

          fly deploy --local-only --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.STUDYPRO_FLY_API_TOKEN }}


      # Fly.io로 Docker 이미지 푸시 및 배포
      #      - name: Deploy Docker Image to Fly.io
      #        run: fly deploy --remote-only

      # Jar 파일 보기
#      - name: Send jar file
#        uses: appleboy/scp-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.HOST }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          source: "./build/libs/*.jar,./src/main/resources/static/swagger/*"
#          target: "/home/ubuntu/server"
#
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#        with:
#          username: ubuntu
#          host: ${{ secrets.HOST }}
#          key: ${{ secrets.PRIVATE_KEY }}
#          script_stop: true
#          script: sudo /home/ubuntu/run_server.sh
